### ISSUE TITLE
Suggestion to refactor logic of checking if ranges overlap

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/sorald-buildbreaker#104]
I was reading Art of Readable Code which you, Simon (in case any 3rd person is reading), recommended. One of the examples in there was about checking for overlap within ranges. This reminded me of when I was reviewing your code, and it did take me time to verify the logic you have written for checking overlap between `Range`s.

https://github.com/SpoonLabs/sorald-buildbreaker/blob/c8e33d15a802d9641325de8f20c86b4992188d8d/src/ranges.ts#L32-L33

A section [1] in the book suggests a more elegant way to solve the problem. It tells us to think the "opposite". In other words, check if they _do not _ overlap as there are only two conditions to think about.
1. `lhs` range ends **before** `rhs` starts. (`lhs.end <= rhs.start`)
2. `lhs` range starts **after** `rhs` ends. (`lhs.start >= rhs.end`)

Note that `<=` is used as the `Range` is exclusive from the end.

[1] **Dustin Boswell, Trevor Foucher.** Chapter 8: Breaking Down Giant Expressions._The Art of Readable Code_. November 2011. pp. 84.

**Comment by slarse** [comment]
Hi @algomaster99, nice observations.

Yeah, that expression is not easy to read. The biggest problem to me isn't that it's large, but that the operations aren't named. And also that there is a redundant `- 1` in there (`lhs.end - 1 >= rhs.start` is equivalent to `lhs.end > rhs.start`). So that's a bit of a brainfart :)

What the expression is really checking here is if either ranges start point is contained in the other range (which, if the ranges overlap, must be true). If we just give that operation a name, suddenly it's not hard to read at all.

```typescript
function rangesOverlap(lhs: Range, rhs: Range): boolean {
  return isInRange(rhs.start, lhs) || isInRange(lhs.start, rhs);
}

function isInRange(value: number, range: Range): boolean {
    return value >= range.start && value < range.end;
}
```

Now, in terms of the `rangesOverlap` function, the only thing you need to consider is whether or not it's actually true that two ranges overlap if-and-only-if the start of either range is contained in the other. The `isInRange` function is a separate entity and its correctness can be separately evaluated, and that is pretty easy to do.

While thinking in opposites makes the "complete" expression smaller, it also requires a different kind of mental gymnastics: double negation. What we then need to check is that the ranges do _not not_ overlap. Then, I think naming is _even more_ important. For example, this is still not crystal clear to me.

```typescript
function rangesOverlap(lhs: Range, rhs: Range): boolean {
    return !(lhs.end <= rhs.start || lhs.start >= rhs.end)
}
```

I would have to think about that for a little bit. However, I would not have to think twice about this:

```typescript
function rangesOverlap(lhs: Range, rhs: Range): boolean {
    return !rangesAreDisjoint(lhs, rhs);
}

function rangesAreDisjoint(lhs: Range, rhs: Range): boolean {
    return lhs.end <= rhs.start || lhs.start >= rhs.end;
}
```

The `rangesOverlap` function is now trivial: of course ranges overlap if they are not disjoint. All I need to verify then is that ranges are disjoint if-and-only-if one ends before the other starts.

For many people (including myself), negations of boolean expressions are _hard_, and so I think it's important to make the negated term as simple as possible.

With all that said, does the `rangesOverlap` warrant refactoring? Yes, of course, it's a big blob of confusion. Feel free to submit a PR with whatever solution you prefer and we'll take it from there.
